import { StyleSheet } from 'react-native';
import { buttonCornerRadius } from '@/constants/buttons';
import { elevation } from '@/constants/elevation';
import { radius } from '@/constants/radius';
import { sizes } from '@/constants/sizes';
import { spacing, semanticSpacing } from '@/constants/spacing';
import { floatingPanelSurface } from '@/constants/surfaces';
import { typography } from '@/constants/typography';
import { zIndex } from '@/constants/zIndex';
import {
  BOOKING_CLOSE_EDGE_INSET,
  BOOKING_CLOSE_ROTATION_PAD,
  BOOKING_HANDLE_HEIGHT,
  BOOKING_HANDLE_TO_TITLE_GAP,
  BOOKING_HANDLE_TOP,
  BOOKING_SHEET_HEADER_HEIGHT,
  BOOKING_SHEET_PADDING_H,
  BOOKING_TITLE_LINE_HEIGHT,
  BOOKING_TITLE_TO_CONTENT_GAP,
  GREETING_LEFT_INSET,
  SCREEN_WIDTH,
} from './homeUtils';

export const darkMapStyle = [
  { elementType: 'geometry', stylers: [{ color: '#1d2c4d' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#8ec3b9' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#1a3646' }] },
  { featureType: 'administrative.country', elementType: 'geometry.stroke', stylers: [{ color: '#4b6878' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#304a7d' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#98a5be' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#0e1626' }] },
];

export const styles = StyleSheet.create({
  container: { flex: 1 },
  recenterBtn: { position: 'absolute', right: semanticSpacing.cardPadding, width: sizes.mapControl.md, height: sizes.mapControl.md, borderRadius: sizes.mapControl.md / 2, alignItems: 'center', justifyContent: 'center', ...elevation.mapControl },
  mapLayerBtn: { position: 'absolute', right: semanticSpacing.cardPadding, width: sizes.mapControl.md, height: sizes.mapControl.md, borderRadius: sizes.mapControl.md / 2, alignItems: 'center', justifyContent: 'center', ...elevation.mapControl },
  youAreHereContainer: { alignItems: 'center' },
  youAreHereBubble: { paddingHorizontal: spacing[10], paddingVertical: spacing[6], borderRadius: radius['3xl'], ...elevation.md, shadowOpacity: 0.3, shadowRadius: spacing[4] },
  youAreHereText: { ...typography.caption, fontFamily: typography.title.fontFamily, color: '#fff' },
  youAreHereTail: { width: 0, height: 0, borderLeftWidth: 6, borderRightWidth: 6, borderTopWidth: 8, borderLeftColor: 'transparent', borderRightColor: 'transparent' },
  // Home bottom panel â€” edge-to-edge bottom sheet (top corners rounded)
  bottomPanel: {
    position: 'absolute',
    bottom: spacing[0],
    left: spacing[0],
    width: SCREEN_WIDTH,
    paddingTop: 22,
    paddingHorizontal: 22,
    gap: spacing[10],
    zIndex: zIndex.sheet,
    overflow: 'visible',
  },
  greeting: { ...typography.h2, textAlign: 'left', marginLeft: GREETING_LEFT_INSET },
  selectRide: { ...typography.bodySmall, fontFamily: typography.label.fontFamily, textAlign: 'left', marginTop: -4, marginLeft: GREETING_LEFT_INSET },
  locationUnavailable: { marginHorizontal: GREETING_LEFT_INSET, padding: spacing[12], borderRadius: radius.card, gap: semanticSpacing.inlineGap },
  locationUnavailableText: { ...typography.label },
  locationUnavailableActions: { flexDirection: 'row', justifyContent: 'space-between', gap: semanticSpacing.rowGap },
  locationUnavailableAction: { ...typography.caption, fontFamily: typography.title.fontFamily },
  vehicleRow: { flexDirection: 'row', gap: semanticSpacing.inlineGap, marginTop: spacing[2], marginHorizontal: GREETING_LEFT_INSET },
  vehicleChip: { flex: 1, flexDirection: 'column', alignItems: 'center', paddingVertical: 7, borderRadius: radius.card, gap: spacing[4], minHeight: sizes.thumbnail.sm, justifyContent: 'center' },
  vehicleLabel: { ...typography.tiny, fontFamily: typography.title.fontFamily },
  continueBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', height: sizes.button.md, borderRadius: buttonCornerRadius(sizes.button.md), gap: semanticSpacing.inlineGap, marginTop: spacing[4], marginHorizontal: GREETING_LEFT_INSET },
  continueBtnText: { ...typography.button },
  // Booking sheet
  bookingSheetWrapper: {
    position: 'absolute',
    top: spacing[0],
    left: spacing[0],
    right: spacing[0],
    zIndex: zIndex.sheet,
    overflow: 'visible',
  },
  bookingSheet: {
    paddingTop: spacing[0],
    gap: spacing[0],
    overflow: 'visible',
  },
  bookingSheetViewport: {
    flex: 1,
    overflow: 'hidden',
  },
  bookingSheetContent: {
    paddingTop: spacing[0],
    gap: spacing[0],
    overflow: 'visible',
  },
  overlayFormSheet: {
    position: 'absolute',
    left: spacing[0],
    right: spacing[0],
    bottom: spacing[0],
    width: SCREEN_WIDTH,
  },
  overlayFormSheetRaised: {
    zIndex: zIndex.modal,
  },
  formSheetSurface: {
    ...floatingPanelSurface,
    // Override the hairline border inherited from floatingPanelSurface — the
    // overlay sheets are now anchored to the tab-bar top edge, so a border
    // would create a visible seam exactly where the sheet meets the navbar.
    // CustomerBottomSheet has no border; these sheets now match.
    borderWidth: spacing[0],
    borderBottomLeftRadius: radius.none,
    borderBottomRightRadius: radius.none,
    borderTopWidth: spacing[0],
    paddingTop: spacing[0],
    gap: spacing[0],
    overflow: 'hidden',
  },
  formSheetBody: {
    paddingHorizontal: BOOKING_SHEET_PADDING_H,
    gap: spacing[10],
    paddingTop: spacing[4],
  },
  bookingFormSheetBody: {
    paddingTop: spacing[0],
  },
  bookingSheetHeader: {
    flexDirection: 'column',
    alignItems: 'stretch',
    paddingLeft: BOOKING_SHEET_PADDING_H,
    paddingRight: 52,
    paddingTop: BOOKING_HANDLE_TOP,
    paddingBottom: BOOKING_TITLE_TO_CONTENT_GAP,
    height: BOOKING_SHEET_HEADER_HEIGHT,
  },
  bookingSheetHandleSlot: {
    alignItems: 'center',
    justifyContent: 'center',
    height: BOOKING_HANDLE_HEIGHT,
    marginBottom: BOOKING_HANDLE_TO_TITLE_GAP,
  },
  bookingSheetHandle: {
    width: sizes.sheet.handleWidth,
    height: BOOKING_HANDLE_HEIGHT,
    borderRadius: radius.xxs,
    backgroundColor: '#3A3A3A',
  },
  bookingSheetTitle: {
    ...typography.title,
    lineHeight: BOOKING_TITLE_LINE_HEIGHT,
  },
  formSheetDragZone: { paddingTop: spacing[0], paddingBottom: spacing[0], marginTop: spacing[0] },
  formSheetHandleTouch: { paddingTop: spacing[6], paddingBottom: spacing[4], marginBottom: spacing[0] },
  formSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: BOOKING_SHEET_PADDING_H,
    paddingRight: 52,
    minHeight: 56,
    paddingTop: 20,
    paddingBottom: 8,
  },
  formSheetHandleSpacer: {
    width: 0,
    height: 0,
  },
  formSheetSubheader: {
    paddingLeft: GREETING_LEFT_INSET,
    paddingRight: 52,
    gap: 4,
    paddingBottom: 2,
  },
  formSheetContent: {
    marginHorizontal: GREETING_LEFT_INSET,
    gap: 10,
  },
  formSheetSubtitle: { ...typography.label, fontFamily: typography.bodySmall.fontFamily },
  formSheetHint: { ...typography.label },
  formSheetCloseAnchor: {
    position: 'absolute',
    top: BOOKING_CLOSE_EDGE_INSET - BOOKING_CLOSE_ROTATION_PAD,
    right: BOOKING_CLOSE_EDGE_INSET - BOOKING_CLOSE_ROTATION_PAD,
    width: 44 + BOOKING_CLOSE_ROTATION_PAD * 2,
    height: 44 + BOOKING_CLOSE_ROTATION_PAD * 2,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: zIndex.header,
  },
  sheetDragZone: { paddingTop: spacing[4], paddingBottom: spacing[2] },
  sheetHandleTouch: { alignSelf: 'stretch', alignItems: 'center', paddingVertical: 10, marginBottom: -2 },
  sheetHandle: { width: sizes.sheet.handleWidth, height: sizes.sheet.handleHeight, borderRadius: radius.xxs, backgroundColor: '#3A3A3A' },
  sheetTitle: { flex: 1, ...typography.title, marginRight: semanticSpacing.inlineGap },
  locationCard: {
    borderRadius: 15,
    padding: 10,
  },
  locRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 5 },
  locDot: { width: 12, height: 12, borderRadius: 6 },
  locLabel: { ...typography.tiny, marginBottom: 2 },
  locInlineLabel: { ...typography.tiny, fontFamily: typography.title.fontFamily, textTransform: 'uppercase' },
  locTextBlock: { flex: 1, gap: 2 },
  locValue: { ...typography.body, fontFamily: typography.label.fontFamily },
  locDivider: { height: 1, marginLeft: 24 },
  currentLocBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingVertical: 1, flexShrink: 1, maxWidth: '52%' },
  currentLocText: { ...typography.caption, fontFamily: typography.label.fontFamily, flexShrink: 1 },
  locationActions: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  rideInfoRow: { flexDirection: 'row', gap: 6 },
  rideInfoCard: { flex: 1, minHeight: 40, flexDirection: 'row', alignItems: 'center', paddingVertical: 4, paddingHorizontal: 9, borderRadius: 14, gap: 5 },
  findDriverAction: { marginTop: 4, paddingTop: 4, paddingBottom: 2 },
  rideInfoText: { flex: 1, gap: 2 },
  rideInfoValue: { ...typography.label, fontFamily: typography.badge.fontFamily },
  rideInfoLabel: { ...typography.tiny, fontFamily: typography.title.fontFamily, textTransform: 'uppercase' },
  suggestionsBox: { borderRadius: 10, marginTop: 4, overflow: 'hidden' },
  suggestionRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 10, paddingHorizontal: 12, borderBottomWidth: StyleSheet.hairlineWidth },
  suggestionText: { flex: 1, ...typography.label, fontFamily: typography.bodySmall.fontFamily },
  vehicleMarkerShadow: {
    position: 'absolute',
    width: 52,
    height: 18,
    borderRadius: 28,
    backgroundColor: 'rgba(0,0,0,0.28)',
    transform: [{ translateY: 8 }, { rotate: '-8deg' }],
  },
  motoSprite: {
    width: 58,
    height: 34,
  },
  motoWheel: {
    position: 'absolute',
    bottom: 3,
    width: 15,
    height: 15,
    borderRadius: 8,
    backgroundColor: '#101010',
    borderWidth: 3,
    borderColor: '#EDEDED',
  },
  motoRearWheel: { left: 3 },
  motoFrontWheel: { right: 3 },
  motoFrame: {
    position: 'absolute',
    left: 15,
    right: 13,
    bottom: 12,
    height: 6,
    borderRadius: 4,
    backgroundColor: '#F8F8F8',
    borderWidth: 1,
    borderColor: '#CFCFCF',
  },
  motoSeat: {
    position: 'absolute',
    left: 17,
    top: 8,
    width: 23,
    height: 9,
    borderRadius: 8,
    backgroundColor: '#151515',
  },
  motoTank: {
    position: 'absolute',
    left: 31,
    top: 11,
    width: 20,
    height: 14,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  motoTankMark: {
    ...typography.caption,
    lineHeight: 13,
    fontFamily: typography.badge.fontFamily,
    color: '#FFFFFF',
  },
  motoFrontFork: {
    position: 'absolute',
    right: 12,
    top: 9,
    width: 3,
    height: 19,
    borderRadius: 2,
    backgroundColor: '#F8F8F8',
    transform: [{ rotate: '-22deg' }],
  },
  motoHandlebar: {
    position: 'absolute',
    right: 7,
    top: 4,
    width: 10,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#151515',
    transform: [{ rotate: '-22deg' }],
  },
  carSprite: {
    width: 31,
    height: 54,
    borderRadius: 15,
    backgroundColor: '#ECECEC',
    borderWidth: 2,
    borderColor: '#9CA3AF',
    alignItems: 'center',
    overflow: 'hidden',
  },
  pickupSprite: {
    width: 34,
    height: 60,
    borderRadius: 11,
  },
  truckSprite: {
    width: 38,
    height: 66,
    borderRadius: 8,
  },
  carTopLight: {
    width: 18,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#F9FAFB',
    marginTop: 3,
  },
  carWindshield: {
    width: 22,
    height: 12,
    borderRadius: 5,
    backgroundColor: '#161616',
    marginTop: 3,
  },
  carCabin: {
    width: 24,
    flex: 1,
    borderRadius: 8,
    marginTop: 3,
    borderWidth: 1,
    borderColor: '#C9CED3',
  },
  cargoBed: {
    position: 'absolute',
    bottom: 9,
    width: 26,
    height: 18,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#B3BAC1',
    backgroundColor: '#BEC5CB',
  },
  carRearGlass: {
    width: 20,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#333333',
    marginBottom: 3,
  },
  carTailLights: {
    position: 'absolute',
    bottom: 0,
    left: 5,
    right: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  carTailLight: {
    width: 8,
    height: 4,
    borderRadius: 3,
    backgroundColor: '#EF4444',
  },
  // Full-screen location search
  locationSearchScreen: { ...StyleSheet.absoluteFillObject, zIndex: 80, flex: 1 },
  locationSearchBody: { flex: 1 },
  locationSearchFixed: { paddingHorizontal: 20 },
  locationSearchScroll: { flex: 1 },
  locationSearchInputWrap: {
    height: 52,
    borderRadius: buttonCornerRadius(52),
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
  },
  locationSearchInput: { flex: 1, ...typography.title, fontFamily: typography.label.fontFamily },
  locationSearchClear: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationSearchList: { paddingTop: 8 },
  locationQuickRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
    marginBottom: 6,
  },
  locationQuickCard: {
    flex: 1,
    minHeight: 62,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 10,
    gap: 6,
  },
  locationQuickIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationQuickText: {
    gap: 1,
  },
  locationQuickTitle: {
    ...typography.caption,
    fontFamily: typography.title.fontFamily,
  },
  locationQuickSub: {
    ...typography.tiny,
    fontFamily: typography.caption.fontFamily,
  },
  locationTabs: {
    flexDirection: 'row',
    padding: 4,
    borderRadius: 12,
    marginTop: 12,
    marginBottom: 8,
    gap: 4,
  },
  locationTab: {
    flex: 1,
    minHeight: 38,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  locationTabText: {
    ...typography.label,
    fontFamily: typography.title.fontFamily,
  },
  locationSearchEmpty: {
    ...typography.bodySmall,
    paddingVertical: 12,
    paddingHorizontal: 4,
  },
  locationSectionTitle: {
    ...typography.tiny,
    fontFamily: typography.badge.fontFamily,
    textTransform: 'uppercase',
    marginTop: 4,
    marginBottom: 6,
  },
  locationSectionTitleAfterSearch: {
    marginTop: 18,
  },
  locationOption: {
    minHeight: 60,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingVertical: 10,
  },
  locationOptionMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 44,
    paddingRight: 4,
  },
  locationOptionIcon: {
    width: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationOptionText: { flex: 1, gap: 2 },
  locationOptionTitle: { ...typography.bodySmall, fontFamily: typography.title.fontFamily },
  locationOptionSub: { ...typography.caption },
  savedLocationMenuButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  saveLocationButton: {
    minWidth: 54,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  saveLocationButtonText: {
    ...typography.caption,
    fontFamily: typography.badge.fontFamily,
  },
  locationEmptyState: {
    minHeight: 118,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  locationEmptyText: {
    ...typography.label,
    textAlign: 'center',
  },
  locationEmptyAction: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationEmptyActionText: {
    ...typography.label,
    fontFamily: typography.badge.fontFamily,
  },
  // Adaptive pill chips for "Save location as" — wrap naturally, width by content.
  saveAsLocationLabels: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  saveAsLocationLabel: {
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveAsLocationLabelText: {
    ...typography.label,
    fontFamily: typography.title.fontFamily,
  },
  saveAsCustomLabelSection: {
    gap: 12,
  },
  saveAsLocationInputWrap: {
    height: 52,
    borderRadius: buttonCornerRadius(52),
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
  },
  saveAsLocationInput: {
    flex: 1,
    ...typography.title,
    fontFamily: typography.label.fontFamily,
  },
  saveAsCustomLabelButton: {
    minHeight: 52,
    borderRadius: buttonCornerRadius(52),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  saveAsCustomLabelButtonText: {
    ...typography.body,
    fontFamily: typography.badge.fontFamily,
  },
  saveLocationLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  saveLocationLabel: {
    minHeight: 36,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveLocationLabelText: {
    ...typography.tiny,
    fontFamily: typography.title.fontFamily,
  },
  customSaveLabelSection: {
    gap: 10,
  },
  customSaveLabelButton: {
    minHeight: 46,
    borderRadius: buttonCornerRadius(46),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  customSaveLabelButtonText: {
    ...typography.label,
    fontFamily: typography.badge.fontFamily,
  },
  // Map picker
  mapPickerContainer: { ...StyleSheet.absoluteFillObject, zIndex: 120 },
  fixedPinContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 46,
    height: 94,
    marginLeft: -23,
    marginTop: -42,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  fixedPinContainerDragging: {
    marginTop: -60,
  },
  uberPin: {
    width: 20,
    height: 54,
    alignItems: 'center',
  },
  uberPinDragging: {
    transform: [{ translateY: -4 }],
  },
  uberPinHead: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#111111',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
    elevation: 8,
  },
  uberPinSquare: {
    width: 4,
    height: 4,
    backgroundColor: '#FFFFFF',
  },
  uberPinStem: {
    width: 2,
    height: 22,
    backgroundColor: '#111111',
  },
  uberPinStemDragging: {
    height: 32,
  },
  uberPinGroundDot: {
    position: 'absolute',
    top: 57,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#111111',
  },
  mapPickerBack: { position: 'absolute', left: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 6, elevation: 6 },
  mapPickerControlsRail: {
    position: 'absolute',
    right: 16,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    gap: 12,
  },
  mapPickerControl: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 6,
  },
  mapPickerHint: { position: 'absolute', top: '18%', alignSelf: 'center', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 6, elevation: 4 },
  mapPickerHintText: { ...typography.label, textAlign: 'center' },
  mapPickerFooter: { position: 'absolute', bottom: 0, left: 0, right: 0, paddingHorizontal: 20 },
  loaderContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 16 },
  loaderText: { ...typography.title },
});
