import { StyleSheet } from 'react-native';
import { buttonCornerRadius } from '@/constants/buttons';
import { floatingPanelSurface } from '@/constants/surfaces';
import {
  BOOKING_CLOSE_EDGE_INSET,
  BOOKING_CLOSE_ROTATION_PAD,
  BOOKING_SHEET_PADDING_H,
  GREETING_LEFT_INSET,
  SCREEN_WIDTH,
} from './homeUtils';

export const darkMapStyle = [
  { elementType: 'geometry', stylers: [{ color: '#1d2c4d' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#8ec3b9' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#1a3646' }] },
  { featureType: 'administrative.country', elementType: 'geometry.stroke', stylers: [{ color: '#4b6878' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#304a7d' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#98a5be' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#0e1626' }] },
];

export const styles = StyleSheet.create({
  container: { flex: 1 },
  recenterBtn: { position: 'absolute', right: 16, width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 6, elevation: 6 },
  mapLayerBtn: { position: 'absolute', right: 16, width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 6, elevation: 6 },
  youAreHereContainer: { alignItems: 'center' },
  youAreHereBubble: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 4, elevation: 4 },
  youAreHereText: { fontSize: 12, fontFamily: 'Inter_600SemiBold', color: '#fff' },
  youAreHereTail: { width: 0, height: 0, borderLeftWidth: 6, borderRightWidth: 6, borderTopWidth: 8, borderLeftColor: 'transparent', borderRightColor: 'transparent' },
  // Home bottom panel â€” edge-to-edge bottom sheet (top corners rounded)
  bottomPanel: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: SCREEN_WIDTH,
    ...floatingPanelSurface,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    paddingTop: 22,
    paddingHorizontal: 22,
    gap: 10,
  },
  greeting: { fontSize: 20, fontFamily: 'Inter_700Bold', textAlign: 'left', marginLeft: GREETING_LEFT_INSET },
  selectRide: { fontSize: 14, fontFamily: 'Inter_500Medium', textAlign: 'left', marginTop: -4, marginLeft: GREETING_LEFT_INSET },
  locationUnavailable: { marginHorizontal: GREETING_LEFT_INSET, padding: 12, borderRadius: 14, gap: 8 },
  locationUnavailableText: { fontSize: 13, fontFamily: 'Inter_500Medium' },
  locationUnavailableActions: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  locationUnavailableAction: { fontSize: 12, fontFamily: 'Inter_600SemiBold' },
  vehicleRow: { flexDirection: 'row', gap: 8, marginTop: 2, marginHorizontal: GREETING_LEFT_INSET },
  vehicleChip: { flex: 1, flexDirection: 'column', alignItems: 'center', paddingVertical: 7, borderRadius: 14, gap: 4, minHeight: 56, justifyContent: 'center' },
  vehicleLabel: { fontSize: 10, fontFamily: 'Inter_600SemiBold' },
  continueBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', height: 50, borderRadius: buttonCornerRadius(50), gap: 8, marginTop: 4, marginHorizontal: GREETING_LEFT_INSET },
  continueBtnText: { fontSize: 16, fontFamily: 'Inter_600SemiBold' },
  // Booking sheet
  bookingSheetWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: SCREEN_WIDTH,
    zIndex: 30,
    overflow: 'visible',
  },
  bookingSheet: {
    ...floatingPanelSurface,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    paddingTop: 0,
    gap: 0,
    overflow: 'visible',
  },
  overlayFormSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    width: SCREEN_WIDTH,
  },
  overlayFormSheetRaised: {
    zIndex: 90,
  },
  formSheetSurface: {
    ...floatingPanelSurface,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopWidth: 0,
    paddingTop: 0,
    gap: 0,
    overflow: 'visible',
  },
  formSheetBody: {
    paddingHorizontal: BOOKING_SHEET_PADDING_H,
    gap: 10,
  },
  formSheetDragZone: { paddingTop: 0, paddingBottom: 0, marginTop: 0 },
  formSheetHandleTouch: { paddingTop: 6, paddingBottom: 4, marginBottom: 0 },
  formSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: GREETING_LEFT_INSET,
    paddingRight: 52,
    minHeight: 44,
  },
  formSheetSubheader: {
    paddingLeft: GREETING_LEFT_INSET,
    paddingRight: 52,
    gap: 4,
    paddingBottom: 2,
  },
  formSheetContent: {
    marginHorizontal: GREETING_LEFT_INSET,
    gap: 10,
  },
  formSheetSubtitle: { fontSize: 13, fontFamily: 'Inter_400Regular', lineHeight: 18 },
  formSheetHint: { fontSize: 13, fontFamily: 'Inter_500Medium' },
  formSheetCloseAnchor: {
    position: 'absolute',
    top: BOOKING_CLOSE_EDGE_INSET - BOOKING_CLOSE_ROTATION_PAD,
    right: BOOKING_CLOSE_EDGE_INSET - BOOKING_CLOSE_ROTATION_PAD,
    width: 44 + BOOKING_CLOSE_ROTATION_PAD * 2,
    height: 44 + BOOKING_CLOSE_ROTATION_PAD * 2,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  sheetDragZone: { paddingTop: 4, paddingBottom: 2 },
  sheetHandleTouch: { alignSelf: 'stretch', alignItems: 'center', paddingVertical: 10, marginBottom: -2 },
  sheetHandle: { width: 40, height: 4, borderRadius: 2, backgroundColor: '#3A3A3A' },
  sheetTitle: { flex: 1, fontSize: 16, fontFamily: 'Inter_600SemiBold', marginRight: 8 },
  locationCard: {
    borderRadius: 15,
    padding: 10,
    marginHorizontal: GREETING_LEFT_INSET,
  },
  locRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 5 },
  locDot: { width: 12, height: 12, borderRadius: 6 },
  locLabel: { fontSize: 11, fontFamily: 'Inter_500Medium', marginBottom: 2 },
  locInlineLabel: { fontSize: 11, fontFamily: 'Inter_600SemiBold', textTransform: 'uppercase' },
  locTextBlock: { flex: 1, gap: 2 },
  locValue: { fontSize: 15, fontFamily: 'Inter_500Medium' },
  locDivider: { height: 1, marginLeft: 24 },
  currentLocBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingVertical: 1, flexShrink: 1, maxWidth: '52%' },
  currentLocText: { fontSize: 12, fontFamily: 'Inter_500Medium', flexShrink: 1 },
  locationActions: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10, marginHorizontal: GREETING_LEFT_INSET },
  rideInfoRow: { flexDirection: 'row', gap: 6, marginHorizontal: GREETING_LEFT_INSET },
  rideInfoCard: { flex: 1, minHeight: 40, flexDirection: 'row', alignItems: 'center', paddingVertical: 4, paddingHorizontal: 9, borderRadius: 14, gap: 5 },
  findDriverAction: { marginTop: 'auto', paddingTop: 4, paddingBottom: 2, marginHorizontal: GREETING_LEFT_INSET },
  rideInfoText: { flex: 1, gap: 2 },
  rideInfoValue: { fontSize: 13, fontFamily: 'Inter_700Bold' },
  rideInfoLabel: { fontSize: 9, fontFamily: 'Inter_600SemiBold', textTransform: 'uppercase' },
  suggestionsBox: { borderRadius: 10, marginTop: 4, overflow: 'hidden' },
  suggestionRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 10, paddingHorizontal: 12, borderBottomWidth: StyleSheet.hairlineWidth },
  suggestionText: { flex: 1, fontSize: 13, fontFamily: 'Inter_400Regular' },
  vehicleMarkerShadow: {
    position: 'absolute',
    width: 52,
    height: 18,
    borderRadius: 28,
    backgroundColor: 'rgba(0,0,0,0.28)',
    transform: [{ translateY: 8 }, { rotate: '-8deg' }],
  },
  motoSprite: {
    width: 58,
    height: 34,
  },
  motoWheel: {
    position: 'absolute',
    bottom: 3,
    width: 15,
    height: 15,
    borderRadius: 8,
    backgroundColor: '#101010',
    borderWidth: 3,
    borderColor: '#EDEDED',
  },
  motoRearWheel: { left: 3 },
  motoFrontWheel: { right: 3 },
  motoFrame: {
    position: 'absolute',
    left: 15,
    right: 13,
    bottom: 12,
    height: 6,
    borderRadius: 4,
    backgroundColor: '#F8F8F8',
    borderWidth: 1,
    borderColor: '#CFCFCF',
  },
  motoSeat: {
    position: 'absolute',
    left: 17,
    top: 8,
    width: 23,
    height: 9,
    borderRadius: 8,
    backgroundColor: '#151515',
  },
  motoTank: {
    position: 'absolute',
    left: 31,
    top: 11,
    width: 20,
    height: 14,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  motoTankMark: {
    fontSize: 12,
    lineHeight: 13,
    fontFamily: 'Inter_700Bold',
    color: '#FFFFFF',
  },
  motoFrontFork: {
    position: 'absolute',
    right: 12,
    top: 9,
    width: 3,
    height: 19,
    borderRadius: 2,
    backgroundColor: '#F8F8F8',
    transform: [{ rotate: '-22deg' }],
  },
  motoHandlebar: {
    position: 'absolute',
    right: 7,
    top: 4,
    width: 10,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#151515',
    transform: [{ rotate: '-22deg' }],
  },
  carSprite: {
    width: 31,
    height: 54,
    borderRadius: 15,
    backgroundColor: '#ECECEC',
    borderWidth: 2,
    borderColor: '#9CA3AF',
    alignItems: 'center',
    overflow: 'hidden',
  },
  pickupSprite: {
    width: 34,
    height: 60,
    borderRadius: 11,
  },
  truckSprite: {
    width: 38,
    height: 66,
    borderRadius: 8,
  },
  carTopLight: {
    width: 18,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#F9FAFB',
    marginTop: 3,
  },
  carWindshield: {
    width: 22,
    height: 12,
    borderRadius: 5,
    backgroundColor: '#161616',
    marginTop: 3,
  },
  carCabin: {
    width: 24,
    flex: 1,
    borderRadius: 8,
    marginTop: 3,
    borderWidth: 1,
    borderColor: '#C9CED3',
  },
  cargoBed: {
    position: 'absolute',
    bottom: 9,
    width: 26,
    height: 18,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#B3BAC1',
    backgroundColor: '#BEC5CB',
  },
  carRearGlass: {
    width: 20,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#333333',
    marginBottom: 3,
  },
  carTailLights: {
    position: 'absolute',
    bottom: 0,
    left: 5,
    right: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  carTailLight: {
    width: 8,
    height: 4,
    borderRadius: 3,
    backgroundColor: '#EF4444',
  },
  // Full-screen location search
  locationSearchScreen: { ...StyleSheet.absoluteFillObject, zIndex: 80, flex: 1 },
  locationSearchBody: { flex: 1 },
  locationSearchFixed: { paddingHorizontal: 20 },
  locationSearchScroll: { flex: 1 },
  locationSearchInputWrap: {
    height: 52,
    borderRadius: buttonCornerRadius(52),
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
  },
  locationSearchInput: { flex: 1, fontSize: 16, fontFamily: 'Inter_500Medium' },
  locationSearchClear: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationSearchList: { paddingTop: 8 },
  locationQuickRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
    marginBottom: 6,
  },
  locationQuickCard: {
    flex: 1,
    minHeight: 62,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 10,
    gap: 6,
  },
  locationQuickIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationQuickText: {
    gap: 1,
  },
  locationQuickTitle: {
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
  },
  locationQuickSub: {
    fontSize: 11,
    fontFamily: 'Inter_400Regular',
  },
  locationTabs: {
    flexDirection: 'row',
    padding: 4,
    borderRadius: 12,
    marginTop: 12,
    marginBottom: 8,
    gap: 4,
  },
  locationTab: {
    flex: 1,
    minHeight: 38,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  locationTabText: {
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
  },
  locationSearchEmpty: {
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
    lineHeight: 20,
    paddingVertical: 12,
    paddingHorizontal: 4,
  },
  locationSectionTitle: {
    fontSize: 11,
    fontFamily: 'Inter_700Bold',
    textTransform: 'uppercase',
    marginTop: 4,
    marginBottom: 6,
  },
  locationSectionTitleAfterSearch: {
    marginTop: 18,
  },
  locationOption: {
    minHeight: 60,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingVertical: 10,
  },
  locationOptionMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 44,
    paddingRight: 4,
  },
  locationOptionIcon: {
    width: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationOptionText: { flex: 1, gap: 2 },
  locationOptionTitle: { fontSize: 14, fontFamily: 'Inter_600SemiBold' },
  locationOptionSub: { fontSize: 12, fontFamily: 'Inter_400Regular' },
  savedLocationMenuButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  saveLocationButton: {
    minWidth: 54,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  saveLocationButtonText: {
    fontSize: 12,
    fontFamily: 'Inter_700Bold',
  },
  locationEmptyState: {
    minHeight: 118,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  locationEmptyText: {
    fontSize: 13,
    fontFamily: 'Inter_500Medium',
    textAlign: 'center',
  },
  locationEmptyAction: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationEmptyActionText: {
    fontSize: 13,
    fontFamily: 'Inter_700Bold',
  },
  saveAsLocationLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  saveAsLocationLabel: {
    minHeight: 44,
    borderRadius: 22,
    borderWidth: 1,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveAsLocationLabelText: {
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
  },
  saveAsCustomLabelSection: {
    gap: 12,
  },
  saveAsLocationInputWrap: {
    height: 52,
    borderRadius: buttonCornerRadius(52),
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
  },
  saveAsLocationInput: {
    flex: 1,
    fontSize: 16,
    fontFamily: 'Inter_500Medium',
  },
  saveAsCustomLabelButton: {
    minHeight: 52,
    borderRadius: buttonCornerRadius(52),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  saveAsCustomLabelButtonText: {
    fontSize: 15,
    fontFamily: 'Inter_700Bold',
  },
  saveLocationLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  saveLocationLabel: {
    minHeight: 36,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveLocationLabelText: {
    fontSize: 9,
    fontFamily: 'Inter_600SemiBold',
  },
  customSaveLabelSection: {
    gap: 10,
  },
  customSaveLabelButton: {
    minHeight: 46,
    borderRadius: buttonCornerRadius(46),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  customSaveLabelButtonText: {
    fontSize: 13,
    fontFamily: 'Inter_700Bold',
  },
  // Map picker
  mapPickerContainer: { ...StyleSheet.absoluteFillObject, zIndex: 120 },
  fixedPinContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 46,
    height: 94,
    marginLeft: -23,
    marginTop: -42,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  fixedPinContainerDragging: {
    marginTop: -60,
  },
  uberPin: {
    width: 20,
    height: 54,
    alignItems: 'center',
  },
  uberPinDragging: {
    transform: [{ translateY: -4 }],
  },
  uberPinHead: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#111111',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
    elevation: 8,
  },
  uberPinSquare: {
    width: 4,
    height: 4,
    backgroundColor: '#FFFFFF',
  },
  uberPinStem: {
    width: 2,
    height: 22,
    backgroundColor: '#111111',
  },
  uberPinStemDragging: {
    height: 32,
  },
  uberPinGroundDot: {
    position: 'absolute',
    top: 57,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#111111',
  },
  mapPickerBack: { position: 'absolute', left: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 6, elevation: 6 },
  mapPickerControlsRail: {
    position: 'absolute',
    right: 16,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    gap: 12,
  },
  mapPickerControl: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 6,
  },
  mapPickerHint: { position: 'absolute', top: '18%', alignSelf: 'center', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 6, elevation: 4 },
  mapPickerHintText: { fontSize: 13, fontFamily: 'Inter_500Medium', textAlign: 'center' },
  mapPickerFooter: { position: 'absolute', bottom: 0, left: 0, right: 0, paddingHorizontal: 20 },
  loaderContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 16 },
  loaderText: { fontSize: 16, fontFamily: 'Inter_600SemiBold' },
});
