import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  headerTitle: { fontSize: 18, fontFamily: 'Inter_600SemiBold' },
  stepIndicator: { fontSize: 14, fontFamily: 'Inter_500Medium' },
  vehicleGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  stepItem: { alignItems: 'center', gap: 4 },
  stepsRow: { flexDirection: 'row', paddingHorizontal: 20, paddingVertical: 12, gap: 8 },
  stepDot: { width: 8, height: 8, borderRadius: 4 },
  stepLabel: { fontSize: 9, fontFamily: 'Inter_500Medium' },
  content: { padding: 20, gap: 16, paddingBottom: 40 },
  section: { gap: 14 },
  sectionTitle: { fontSize: 20, fontFamily: 'Inter_700Bold' },
  sectionSubtitle: { fontSize: 16, fontFamily: 'Inter_600SemiBold', marginTop: 4 },
  sectionDesc: { fontSize: 14, fontFamily: 'Inter_400Regular', lineHeight: 20 },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
  },
  infoLabel: { fontSize: 14, fontFamily: 'Inter_400Regular' },
  infoValue: { fontSize: 14, fontFamily: 'Inter_600SemiBold' },
  inputLabel: { fontSize: 13, fontFamily: 'Inter_500Medium' },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    height: 50,
    borderRadius: 12,
    borderWidth: 1,
  },
  dropdownText: { fontSize: 15, fontFamily: 'Inter_400Regular', flex: 1 },
  dropdownList: {
    borderWidth: 1,
    borderRadius: 12,
    marginTop: 2,
    overflow: 'hidden',
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
  },
  dropdownItemText: { fontSize: 14, fontFamily: 'Inter_400Regular' },
  errorText: { fontSize: 12, fontFamily: 'Inter_400Regular', marginTop: -8 },
  plateGuide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    marginTop: 6,
    paddingHorizontal: 2,
  },
  plateGuideText: { flex: 1, fontSize: 11, fontFamily: 'Inter_400Regular', lineHeight: 16 },
  plateWarning: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'flex-start',
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    marginTop: 4,
  },
  plateWarningText: { flex: 1, fontSize: 12, fontFamily: 'Inter_400Regular', lineHeight: 16 },
  // Selfie
  selfieBtn: {
    alignItems: 'center',
    gap: 8,
    paddingVertical: 28,
    borderRadius: 16,
    borderWidth: 1.5,
    borderStyle: 'dashed',
  },
  selfieIconCircle: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center' },
  selfieLabel: { fontSize: 16, fontFamily: 'Inter_600SemiBold' },
  selfiePreviewRow: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  selfieImage: { width: 80, height: 80, borderRadius: 40 },
  selfieRetakeBtn: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'center',
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
  },
  // Documents
  docRow: { gap: 8 },
  docHeader: { gap: 2 },
  docLabel: { fontSize: 14, fontFamily: 'Inter_500Medium' },
  docHint: { fontSize: 11, fontFamily: 'Inter_400Regular' },
  docFaceLabel: { fontSize: 11, fontFamily: 'Inter_600SemiBold', textTransform: 'uppercase', letterSpacing: 0.5 },
  docUploadBtn: {
    flex: 1,
    height: 80,
    borderWidth: 1.5,
    borderRadius: 14,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  docUploadText: { fontSize: 14, fontFamily: 'Inter_500Medium' },
  docPreviewRow: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  docThumb: { width: 70, height: 70, borderRadius: 10 },
  docUploaded: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
  },
  docUploadedText: { fontSize: 13, fontFamily: 'Inter_600SemiBold' },
  docActionRow: { flexDirection: 'row', gap: 10 },
  docChangeBtn: {
    flex: 1,
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'center',
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
  },
  docChangeBtnText: { fontSize: 12, fontFamily: 'Inter_500Medium' },
  docAddBackBtn: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: 'dashed',
  },
  docAddBackText: { fontSize: 13, fontFamily: 'Inter_500Medium' },
  // Payment
  providerRow: { flexDirection: 'row', gap: 12 },
  providerCard: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
    padding: 16,
    borderRadius: 14,
    borderWidth: 1.5,
    position: 'relative',
  },
  providerName: { fontSize: 14, fontFamily: 'Inter_600SemiBold' },
  providerLogo: {
    width: '100%',
    height: 48,
    borderRadius: 8,
  },
  providerCheck: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Terms — bare row, no card border
  termsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 4,
  },
  termsCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
    flexShrink: 0,
  },
  termsText: { flex: 1, fontSize: 14, fontFamily: 'Inter_500Medium', lineHeight: 22 },
  termsLink: { fontFamily: 'Inter_600SemiBold', textDecorationLine: 'underline' },
  notice: {
    flexDirection: 'row',
    gap: 8,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'flex-start',
  },
  noticeText: { flex: 1, fontSize: 12, fontFamily: 'Inter_400Regular', lineHeight: 18 },
});
