import { typography } from '@/constants/typography';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  headerTitle: { ...typography.h3,  },
  stepIndicator: { ...typography.bodySmall,  },
  vehicleGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  stepItem: { alignItems: 'center', gap: 4 },
  stepsRow: { flexDirection: 'row', paddingHorizontal: 20, paddingVertical: 12, gap: 8 },
  stepDot: { width: 8, height: 8, borderRadius: 4 },
  stepLabel: { ...typography.tiny,  },
  content: { padding: 20, gap: 16, paddingBottom: 40 },
  section: { gap: 14 },
  sectionTitle: { ...typography.h2,  },
  sectionSubtitle: { ...typography.title, marginTop: 4 },
  sectionDesc: { ...typography.bodySmall, lineHeight: 20 },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
  },
  infoLabel: { ...typography.bodySmall,  },
  infoValue: { ...typography.bodySmall,  },
  inputLabel: { ...typography.label,  },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    height: 50,
    borderRadius: 12,
    borderWidth: 1,
  },
  dropdownText: { ...typography.body, flex: 1 },
  dropdownList: {
    borderWidth: 1,
    borderRadius: 12,
    marginTop: 2,
    overflow: 'hidden',
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
  },
  dropdownItemText: { ...typography.bodySmall,  },
  errorText: { ...typography.caption, marginTop: -8 },
  plateGuide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    marginTop: 6,
    paddingHorizontal: 2,
  },
  plateGuideText: { flex: 1, ...typography.tiny, lineHeight: 16 },
  plateWarning: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'flex-start',
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    marginTop: 4,
  },
  plateWarningText: { flex: 1, ...typography.caption, lineHeight: 16 },
  // Selfie
  selfieBtn: {
    alignItems: 'center',
    gap: 8,
    paddingVertical: 28,
    borderRadius: 16,
    borderWidth: 1.5,
    borderStyle: 'dashed',
  },
  selfieIconCircle: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center' },
  selfieLabel: { ...typography.title,  },
  selfiePreviewRow: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  selfieImage: { width: 80, height: 80, borderRadius: 40 },
  selfieRetakeBtn: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'center',
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
  },
  // Documents
  docRow: { gap: 8 },
  docHeader: { gap: 2 },
  docLabel: { ...typography.bodySmall,  },
  docHint: { ...typography.tiny,  },
  docFaceLabel: { ...typography.tiny, textTransform: 'uppercase', letterSpacing: 0.5 },
  docUploadBtn: {
    flex: 1,
    height: 80,
    borderWidth: 1.5,
    borderRadius: 14,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  docUploadText: { ...typography.button },
  docPreviewCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  docThumb: { width: 76, height: 76, borderRadius: 10 },
  docPreviewContent: { flex: 1, gap: 10 },
  docCapturedRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  docCapturedIcon: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  docCapturedCopy: { flex: 1, gap: 1 },
  docUploaded: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
  },
  docUploadedText: { ...typography.label,  },
  docActionRow: { flexDirection: 'row', gap: 10 },
  docChangeBtn: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 17,
    borderWidth: 1,
  },
  docChangeBtnText: { ...typography.button },
  // Payment
  providerRow: { flexDirection: 'row', gap: 12 },
  providerCard: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
    padding: 16,
    borderRadius: 14,
    borderWidth: 1.5,
    position: 'relative',
  },
  providerName: { ...typography.bodySmall,  },
  providerLogo: {
    width: '100%',
    height: 48,
    borderRadius: 8,
  },
  providerCheck: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Terms — bare row, no card border
  termsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 4,
  },
  termsCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
    flexShrink: 0,
  },
  termsText: { flex: 1, ...typography.bodySmall, lineHeight: 22 },
  termsLink: { textDecorationLine: 'underline' },
  notice: {
    flexDirection: 'row',
    gap: 8,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'flex-start',
  },
  noticeText: { flex: 1, ...typography.caption, lineHeight: 18 },
});
