import { typography } from '@/constants/typography';
import { radius } from '@/constants/radius';
import { sizes } from '@/constants/sizes';
import { spacing, semanticSpacing } from '@/constants/spacing';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: semanticSpacing.screenPadding,
    paddingBottom: spacing[16],
  },
  headerTitle: { ...typography.h3,  },
  stepIndicator: { ...typography.bodySmall,  },
  vehicleGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: semanticSpacing.rowGap },
  stepItem: { alignItems: 'center', gap: spacing[4] },
  stepsRow: { flexDirection: 'row', paddingHorizontal: semanticSpacing.screenPadding, paddingVertical: spacing[12], gap: semanticSpacing.inlineGap },
  stepDot: { width: spacing[8], height: spacing[8], borderRadius: radius.xs },
  stepLabel: { ...typography.tiny,  },
  content: { padding: semanticSpacing.screenPadding, gap: semanticSpacing.comfortableGap, paddingBottom: spacing[40] },
  section: { gap: semanticSpacing.listItemPadding },
  sectionTitle: { ...typography.h2,  },
  sectionSubtitle: { ...typography.title, marginTop: spacing[4] },
  sectionDesc: { ...typography.bodySmall, lineHeight: 20 },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: semanticSpacing.listItemPadding,
    borderRadius: radius.input,
    borderWidth: 1,
  },
  infoLabel: { ...typography.bodySmall,  },
  infoValue: { ...typography.bodySmall,  },
  inputLabel: { ...typography.label,  },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: semanticSpacing.listItemPadding,
    height: sizes.button.md,
    borderRadius: radius.input,
    borderWidth: 1,
  },
  dropdownText: { ...typography.body, flex: 1 },
  dropdownList: {
    borderWidth: 1,
    borderRadius: radius.input,
    marginTop: spacing[2],
    overflow: 'hidden',
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: semanticSpacing.listItemPadding,
    paddingVertical: spacing[12],
    borderBottomWidth: 0.5,
  },
  dropdownItemText: { ...typography.bodySmall,  },
  errorText: { ...typography.caption, marginTop: -spacing[8] },
  plateGuide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: semanticSpacing.compactGap,
    marginTop: spacing[6],
    paddingHorizontal: spacing[2],
  },
  plateGuideText: { flex: 1, ...typography.tiny, lineHeight: 16 },
  plateWarning: {
    flexDirection: 'row',
    gap: semanticSpacing.compactGap,
    alignItems: 'flex-start',
    padding: spacing[10],
    borderRadius: radius.md,
    borderWidth: 1,
    marginTop: spacing[4],
  },
  plateWarningText: { flex: 1, ...typography.caption, lineHeight: 16 },
  // Selfie
  selfieBtn: {
    alignItems: 'center',
    gap: semanticSpacing.inlineGap,
    paddingVertical: spacing[28],
    borderRadius: radius['2xl'],
    borderWidth: 1.5,
    borderStyle: 'dashed',
  },
  selfieIconCircle: { width: sizes.thumbnail.sm, height: sizes.thumbnail.sm, borderRadius: spacing[28], alignItems: 'center', justifyContent: 'center' },
  selfieLabel: { ...typography.title,  },
  selfiePreviewRow: { flexDirection: 'row', gap: semanticSpacing.rowGap, alignItems: 'center' },
  selfieImage: { width: sizes.avatar.xxl, height: sizes.avatar.xxl, borderRadius: spacing[40] },
  selfieRetakeBtn: {
    flexDirection: 'row',
    gap: semanticSpacing.compactGap,
    alignItems: 'center',
    justifyContent: 'center',
    height: sizes.iconButton.sm,
    borderRadius: radius.sm,
    borderWidth: 1,
    paddingHorizontal: spacing[12],
  },
  // Documents
  docRow: { gap: semanticSpacing.inlineGap },
  docHeader: { gap: spacing[2] },
  docLabel: { ...typography.bodySmall,  },
  docHint: { ...typography.tiny,  },
  docFaceLabel: { ...typography.tiny, textTransform: 'uppercase', letterSpacing: 0.5 },
  docUploadBtn: {
    flex: 1,
    height: sizes.avatar.xxl,
    borderWidth: 1.5,
    borderRadius: radius.card,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    gap: semanticSpacing.inlineGap,
  },
  docUploadText: { ...typography.button },
  docPreviewCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: semanticSpacing.rowGap,
  },
  docThumb: { width: sizes.thumbnail.lg, height: sizes.thumbnail.lg, borderRadius: radius.md },
  docPreviewContent: { flex: 1, gap: spacing[10] },
  docCapturedRow: { flexDirection: 'row', alignItems: 'center', gap: semanticSpacing.inlineGap },
  docCapturedIcon: { width: sizes.avatar.xs, height: sizes.avatar.xs, borderRadius: radius.xl, alignItems: 'center', justifyContent: 'center' },
  docCapturedCopy: { flex: 1, gap: 1 },
  docUploaded: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: semanticSpacing.compactGap,
    paddingHorizontal: spacing[10],
    paddingVertical: spacing[6],
    borderRadius: radius.sm,
    borderWidth: 1,
  },
  docUploadedText: { ...typography.label,  },
  docActionRow: { flexDirection: 'row', gap: spacing[10] },
  docChangeBtn: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: semanticSpacing.compactGap,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: sizes.iconButton.sm,
    paddingHorizontal: spacing[12],
    borderRadius: 17,
    borderWidth: 1,
  },
  docChangeBtnText: { ...typography.button },
  // Payment
  providerRow: { flexDirection: 'row', gap: semanticSpacing.rowGap },
  providerCard: {
    flex: 1,
    alignItems: 'center',
    gap: semanticSpacing.inlineGap,
    padding: semanticSpacing.cardPadding,
    borderRadius: radius.card,
    borderWidth: 1.5,
    position: 'relative',
  },
  providerName: { ...typography.bodySmall,  },
  providerLogo: {
    width: '100%',
    height: sizes.input.md,
    borderRadius: radius.sm,
  },
  providerCheck: {
    position: 'absolute',
    top: spacing[8],
    right: spacing[8],
    width: spacing[20],
    height: spacing[20],
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Terms — bare row, no card border
  termsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: semanticSpacing.rowGap,
    paddingVertical: spacing[4],
  },
  termsCheckbox: {
    width: spacing[24],
    height: spacing[24],
    borderRadius: radius.xs + spacing[2],
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
    flexShrink: 0,
  },
  termsText: { flex: 1, ...typography.bodySmall, lineHeight: 22 },
  termsLink: { textDecorationLine: 'underline' },
  notice: {
    flexDirection: 'row',
    gap: semanticSpacing.inlineGap,
    padding: spacing[12],
    borderRadius: radius.input,
    borderWidth: 1,
    alignItems: 'flex-start',
  },
  noticeText: { flex: 1, ...typography.caption, lineHeight: 18 },
});
