import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  page: { flex: 1, minHeight: 0 },
  topSection: { paddingHorizontal: 16, gap: 10, paddingBottom: 6 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  identityRow: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 3,
    ...Platform.select({
      web: { boxShadow: '0 4px 12px rgba(0,0,0,0.12)' },
    }),
  },
  avatarInitial: { fontSize: 23, fontFamily: 'Inter_600SemiBold', color: '#FFFFFF', lineHeight: 28 },
  avatarImage: { width: 46, height: 46, borderRadius: 23 },
  identityText: { flex: 1, minWidth: 0 },
  title: { fontSize: 20, fontFamily: 'Inter_700Bold' },
  subtitle: { fontSize: 12, fontFamily: 'Inter_500Medium', marginTop: 2 },
  subtitleRow: { flexDirection: 'row', alignItems: 'center', gap: 7, minWidth: 0 },
  ratingRow: { flexDirection: 'row', alignItems: 'center', gap: 3, marginTop: 2 },
  ratingText: { fontSize: 12, fontFamily: 'Inter_700Bold' },
  iconButton: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  statusBanner: { minHeight: 46, borderRadius: 14, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 10 },
  statusText: { flex: 1, fontSize: 13, fontFamily: 'Inter_600SemiBold' },
  tripSummaryCard: {
    borderRadius: 14,
    paddingHorizontal: 11,
    paddingVertical: 9,
    gap: 7,
  },
  tripRoute: { flexDirection: 'row', gap: 9 },
  tripRouteTrack: { width: 12, alignItems: 'center', paddingTop: 3 },
  tripDot: { width: 8, height: 8, borderRadius: 4 },
  tripDotSquare: { borderRadius: 2 },
  tripConnector: { flex: 1, width: 2, minHeight: 14, marginVertical: 2, borderRadius: 1 },
  tripStops: { flex: 1, minWidth: 0, gap: 8 },
  tripStop: { gap: 1 },
  tripStopLabel: {
    fontSize: 9,
    fontFamily: 'Inter_700Bold',
    textTransform: 'uppercase',
    letterSpacing: 0.35,
  },
  tripStopValue: { fontSize: 13, fontFamily: 'Inter_500Medium', lineHeight: 17 },
  tripGenericNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
  },
  tripGenericText: { flex: 1, fontSize: 11, fontFamily: 'Inter_500Medium' },
  tripStatsRow: {
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingTop: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tripStatInline: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  tripStatLabel: { fontSize: 11, fontFamily: 'Inter_600SemiBold' },
  tripStatValue: { fontSize: 13, fontFamily: 'Inter_700Bold' },
  offerCard: { borderRadius: 18, padding: 18, gap: 6 },
  offerLabel: { fontSize: 11, fontFamily: 'Inter_700Bold', textTransform: 'uppercase' },
  offerAmount: { fontSize: 34, fontFamily: 'Inter_700Bold' },
  offerDelta: { fontSize: 13, fontFamily: 'Inter_700Bold' },
  trustCopy: { fontSize: 12, fontFamily: 'Inter_400Regular', lineHeight: 18 },
  chatStatusCard: {
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 11,
    gap: 10,
  },
  chatStatusTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  chatStatusIcon: {
    width: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatStatusCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  chatStatusTitle: {
    fontSize: 15,
    fontFamily: 'Inter_600SemiBold',
  },
  chatStatusHint: {
    fontSize: 13,
    fontFamily: 'Inter_400Regular',
    lineHeight: 18,
  },
  chatStatusHintEmphasis: {
    fontFamily: 'Inter_600SemiBold',
  },
  offersLeftBadge: {
    minWidth: 40,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 10,
    alignItems: 'center',
  },
  offersLeftText: {
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
    lineHeight: 18,
  },
  offersLeftLabel: {
    fontSize: 10,
    fontFamily: 'Inter_500Medium',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  offerProgressRow: {
    flexDirection: 'row',
    gap: 6,
  },
  offerProgressSegment: {
    flex: 1,
    height: 4,
    borderRadius: 2,
  },
  offerProgressLabel: {
    fontSize: 12,
    fontFamily: 'Inter_500Medium',
  },
  messagesScroll: { flex: 1, minHeight: 0 },
  timeline: { gap: 6, paddingBottom: 12, paddingTop: 4 },
  emptyTimeline: { fontSize: 15, fontFamily: 'Inter_400Regular', textAlign: 'center', paddingVertical: 24, lineHeight: 22 },
  timelineItem: { flexDirection: 'row', width: '100%' },
  timelineLeftItem: { justifyContent: 'flex-start', paddingRight: 52 },
  timelineRightItem: { justifyContent: 'flex-end', paddingLeft: 52 },
  timelineSystemItem: { alignItems: 'center', paddingVertical: 4 },
  bubble: {
    maxWidth: '100%',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 6,
    gap: 4,
  },
  bubbleOutgoing: {
    borderTopRightRadius: 4,
  },
  bubbleIncoming: {
    borderTopLeftRadius: 4,
  },
  bubbleBody: {
    fontSize: 16,
    fontFamily: 'Inter_400Regular',
    lineHeight: 22,
  },
  bubbleOfferAmount: {
    fontSize: 17,
    fontFamily: 'Inter_600SemiBold',
    lineHeight: 22,
  },
  bubbleFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
    alignSelf: 'flex-end',
    marginTop: 2,
  },
  bubbleTime: {
    fontSize: 11,
    fontFamily: 'Inter_400Regular',
  },
  systemBubble: {
    maxWidth: '88%',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  systemBubbleText: {
    fontSize: 13,
    fontFamily: 'Inter_400Regular',
    lineHeight: 18,
    textAlign: 'center',
  },
  typingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 16,
    borderTopLeftRadius: 4,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  typingText: {
    fontSize: 15,
    fontFamily: 'Inter_400Regular',
  },
  lockedBadge: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionPanel: { flexShrink: 0, paddingHorizontal: 14, paddingTop: 10 },
  limitBanner: { flexDirection: 'row', alignItems: 'center', gap: 8, padding: 10, borderRadius: 12 },
  limitText: { flex: 1, fontSize: 12, fontFamily: 'Inter_500Medium' },
  inputRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  currencyBadge: { height: 48, paddingHorizontal: 12, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  currencyText: { fontSize: 13, fontFamily: 'Inter_700Bold' },
  offerInput: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    fontSize: 15,
    fontFamily: 'Inter_600SemiBold',
  },
  offerInputPlaceholder: {
    fontSize: 13,
    fontFamily: 'Inter_500Medium',
  },
  sendBtn: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center' },
  mainActions: {
    flexDirection: 'row',
    gap: 9,
    alignItems: 'center',
    paddingTop: 10,
  },
  bottomChrome: { flexShrink: 0 },
  inputDock: {
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 8,
  },
  actionFlexNarrow: { flex: 0.9, minWidth: 0 },
  actionFlexWide: { flex: 1.25, minWidth: 0 },
  actionFlexPrimary: { flex: 1.4, minWidth: 0 },
  modalIcon: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center' },
  modalTitle: { fontSize: 20, fontFamily: 'Inter_700Bold', textAlign: 'center' },
  modalSub: { fontSize: 13, fontFamily: 'Inter_400Regular', lineHeight: 20, textAlign: 'center' },
  acceptFareDialogCard: { borderWidth: 0 },
  acceptSummary: { width: '100%', borderRadius: 14, padding: 12, gap: 9 },
  acceptSummaryRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  acceptSummaryTotal: { paddingTop: 9, borderTopWidth: StyleSheet.hairlineWidth },
  acceptSummaryLabel: { fontSize: 11, fontFamily: 'Inter_700Bold', textTransform: 'uppercase' },
  acceptSummaryValue: { flex: 1, textAlign: 'right', fontSize: 12, fontFamily: 'Inter_600SemiBold' },
  acceptSummaryAmount: { fontSize: 15, fontFamily: 'Inter_700Bold' },
  modalActions: { flexDirection: 'row', gap: 10, width: '100%' },
  modalActionBtn: { flex: 1 },
});
