import { Platform, StyleSheet } from 'react-native';
import { typography } from '@/constants/typography';

export const styles = StyleSheet.create({
  page: { flex: 1, minHeight: 0 },
  topSection: { paddingHorizontal: 16, gap: 10, paddingBottom: 6 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  identityRow: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 3,
    ...Platform.select({
      web: { boxShadow: '0 4px 12px rgba(0,0,0,0.12)' },
    }),
  },
  avatarInitial: { ...typography.h2, fontFamily: typography.title.fontFamily, color: '#FFFFFF', lineHeight: 28 },
  avatarImage: { width: 46, height: 46, borderRadius: 23 },
  identityText: { flex: 1, minWidth: 0 },
  title: { ...typography.h2, fontFamily: typography.badge.fontFamily},
  subtitle: { ...typography.caption, fontFamily: typography.label.fontFamily, marginTop: 2 },
  subtitleRow: { flexDirection: 'row', alignItems: 'center', gap: 7, minWidth: 0 },
  ratingRow: { flexDirection: 'row', alignItems: 'center', gap: 3, marginTop: 2 },
  ratingText: { ...typography.caption, fontFamily: typography.badge.fontFamily},
  iconButton: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  statusBanner: { minHeight: 46, borderRadius: 14, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 10 },
  statusText: { flex: 1, ...typography.label, fontFamily: typography.title.fontFamily},
  tripSummaryCard: {
    borderRadius: 14,
    paddingHorizontal: 11,
    paddingVertical: 9,
    gap: 7,
  },
  tripRoute: { flexDirection: 'row', gap: 9 },
  tripRouteTrack: { width: 12, alignItems: 'center', paddingTop: 3 },
  tripDot: { width: 8, height: 8, borderRadius: 4 },
  tripDotSquare: { borderRadius: 2 },
  tripConnector: { flex: 1, width: 2, minHeight: 14, marginVertical: 2, borderRadius: 1 },
  tripStops: { flex: 1, minWidth: 0, gap: 8 },
  tripStop: { gap: 1 },
  tripStopLabel: {
    ...typography.tiny,
    fontFamily: typography.badge.fontFamily,
    textTransform: 'uppercase',
    letterSpacing: 0.35,
  },
  tripStopValue: { ...typography.label, fontFamily: typography.label.fontFamily, lineHeight: 17 },
  tripGenericNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
  },
  tripGenericText: { flex: 1, ...typography.tiny, fontFamily: typography.label.fontFamily},
  tripStatsRow: {
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingTop: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tripStatInline: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  tripStatLabel: { ...typography.tiny, fontFamily: typography.title.fontFamily},
  tripStatValue: { ...typography.label, fontFamily: typography.badge.fontFamily},
  offerCard: { borderRadius: 18, padding: 18, gap: 6 },
  offerLabel: { ...typography.tiny, fontFamily: typography.badge.fontFamily, textTransform: 'uppercase' },
  offerAmount: { ...typography.displayXL, fontFamily: typography.badge.fontFamily},
  offerDelta: { ...typography.label, fontFamily: typography.badge.fontFamily},
  trustCopy: { ...typography.caption, fontFamily: typography.body.fontFamily, lineHeight: 18 },
  chatStatusCard: {
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 11,
    gap: 10,
  },
  chatStatusTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  chatStatusIcon: {
    width: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatStatusCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  chatStatusTitle: {
    ...typography.body,
    fontFamily: typography.title.fontFamily,
  },
  chatStatusHint: {
    ...typography.label,
    lineHeight: 18,
  },
  chatStatusHintEmphasis: {
    fontFamily: typography.title.fontFamily,
  },
  offersLeftBadge: {
    minWidth: 40,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 10,
    alignItems: 'center',
  },
  offersLeftText: {
    ...typography.title,
    fontFamily: typography.badge.fontFamily,
    lineHeight: 18,
  },
  offersLeftLabel: {
    ...typography.tiny,
    fontFamily: typography.label.fontFamily,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  offerProgressRow: {
    flexDirection: 'row',
    gap: 6,
  },
  offerProgressSegment: {
    flex: 1,
    height: 4,
    borderRadius: 2,
  },
  offerProgressLabel: {
    ...typography.caption,
    fontFamily: typography.label.fontFamily,
  },
  messagesScroll: { flex: 1, minHeight: 0 },
  timeline: { gap: 6, paddingBottom: 12, paddingTop: 4 },
  emptyTimeline: { ...typography.body, fontFamily: typography.body.fontFamily, textAlign: 'center', paddingVertical: 24, lineHeight: 22 },
  timelineItem: { flexDirection: 'row', width: '100%' },
  timelineLeftItem: { justifyContent: 'flex-start', paddingRight: 52 },
  timelineRightItem: { justifyContent: 'flex-end', paddingLeft: 52 },
  timelineSystemItem: { alignItems: 'center', paddingVertical: 4 },
  bubble: {
    maxWidth: '100%',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 6,
    gap: 4,
  },
  bubbleOutgoing: {
    borderTopRightRadius: 4,
  },
  bubbleIncoming: {
    borderTopLeftRadius: 4,
  },
  bubbleBody: {
    ...typography.title,
    lineHeight: 22,
  },
  bubbleOfferAmount: {
    ...typography.title,
    fontFamily: typography.title.fontFamily,
    lineHeight: 22,
  },
  bubbleFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
    alignSelf: 'flex-end',
    marginTop: 2,
  },
  bubbleTime: {
    ...typography.tiny,
  },
  // Delivery status of the viewer's own outgoing message — never applied to
  // anything that came from the server (already confirmed delivered).
  bubblePending: { opacity: 0.65 },
  deliveryIndicator: { marginLeft: 2 },
  retryHint: {
    ...typography.tiny,
    marginTop: 2,
    textAlign: 'right',
  },
  systemBubble: {
    maxWidth: '88%',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  systemBubbleText: {
    ...typography.label,
    lineHeight: 18,
    textAlign: 'center',
  },
  typingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 16,
    borderTopLeftRadius: 4,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  typingText: {
    ...typography.body,
  },
  lockedBadge: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionPanel: { flexShrink: 0, paddingHorizontal: 14, paddingTop: 10 },
  limitBanner: { flexDirection: 'row', alignItems: 'center', gap: 8, padding: 10, borderRadius: 12 },
  limitText: { flex: 1, ...typography.caption, fontFamily: typography.label.fontFamily},
  inputRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  fareErrorText: { ...typography.caption, fontFamily: typography.label.fontFamily, marginTop: 6, marginLeft: 4 },
  currencyBadge: { height: 48, paddingHorizontal: 12, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  currencyText: { ...typography.label, fontFamily: typography.badge.fontFamily},
  offerInput: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    ...typography.body,
    fontFamily: typography.title.fontFamily,
  },
  offerInputPlaceholder: {
    ...typography.label,
    fontFamily: typography.label.fontFamily,
  },
  sendBtn: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center' },
  messageInput: {
    flex: 1,
    minHeight: 48,
    maxHeight: 96,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    ...typography.body,
    fontFamily: typography.body.fontFamily,
  },
  messageRowSpacing: { marginTop: 8 },
  mainActions: {
    flexDirection: 'row',
    gap: 9,
    alignItems: 'center',
    paddingTop: 10,
  },
  bottomChrome: { flexShrink: 0 },
  inputDock: {
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 8,
  },
  actionFlexNarrow: { flex: 0.9, minWidth: 0 },
  actionFlexWide: { flex: 1.25, minWidth: 0 },
  actionFlexPrimary: { flex: 1.4, minWidth: 0 },
  modalIcon: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center' },
  modalTitle: { ...typography.h2, fontFamily: typography.badge.fontFamily, textAlign: 'center' },
  modalSub: { ...typography.label, fontFamily: typography.body.fontFamily, lineHeight: 20, textAlign: 'center' },
  acceptFareDialogCard: { borderWidth: 0 },
  acceptSummary: { width: '100%', borderRadius: 14, padding: 12, gap: 9 },
  acceptSummaryRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  acceptSummaryTotal: { paddingTop: 9, borderTopWidth: StyleSheet.hairlineWidth },
  acceptSummaryLabel: { ...typography.tiny, fontFamily: typography.badge.fontFamily, textTransform: 'uppercase' },
  acceptSummaryValue: { flex: 1, textAlign: 'right', ...typography.caption, fontFamily: typography.title.fontFamily},
  acceptSummaryAmount: { ...typography.body, fontFamily: typography.badge.fontFamily},
  modalActions: { flexDirection: 'row', gap: 10, width: '100%' },
  modalActionBtn: { flex: 1 },
});
