export {
  useBoardPassengerMutation,
  useCancelIntercityBookingMutation,
  useConfirmBookingMutation,
  useDriverIntercityTripsQuery,
  useHoldSeatsMutation,
  useIntercityBookingQuery,
  useIntercityBookingsQuery,
  useIntercityCorridorsQuery,
  useIntercityDriverVehiclesQuery,
  useIntercityEligibility,
  useIntercityManifestQuery,
  useIntercityTripLifecycleMutation,
  useIntercityTripQuery,
  useIntercityTripSearchQuery,
  useMarkNoShowMutation,
  usePublishIntercityTripMutation,
} from '@/query/hooks/useIntercityQueries';
